<?php
if($this->post){
    print_r($this->post);
}else{
?>
<br /><br />

	<form method='POST' class="panel panel-info" action='addtag' id="zend_form" class="form-inline" >
        <div class="panel-heading">
        <h4>Dodaj artykuł!</h4>
        </div>
        <div style="margin: auto;width:99%">
            <br>
            <label for="title">Tytuł</label><br>
            <input type="text" name="title" maxlength="50"/><br>
           
            <label for="symbol">Kategoria</label><br>
            <select name="symbol">
                <option disabled="disabled">Wybierz kategorię</option>
            </select><br>
            
            <label for="text">Opis</label><br>
            <textarea name="text" cols="60" rows="15"></textarea>
            <br><br>
            <input class="btn btn-info" type="submit" value="Wyślij" />
            <br>
        </div>
    </form>

<?php
}
?>
