<br /><br />
<div id="view-content container">

    <hr>
    <h3 style="text-align: center">
        <?php print $this->article['title']?> 
        <span style="font-weight: normal; font-size: 0.4em">
            <i> by <span style="font-size: 1.8em"><?php print $this->article->autor?></i>
        </span>
    </h3>
    <?php print $this->article['text']?> 
    <hr>
</div>
<div class="container-fluid">
    <?= $this->commentForm ?>
</div>
<style>
    form.form textarea { height: 5em; width: 70%}
</style>
    