<?php echo $this->headTitle("Kategorie Tematyczne");?>
<br><br>
<div id="view-content">

<?php 
    foreach($this->listTags as $tag):
        $url = $this->url([
            'controller' => 'artykuly',
            'action'     => 'kategoria',
            'id'         => $tag['tags_id']
        ],  'default')
?>
    <a href="<?= $url ?>" style="text-decoration: none">
        <div class="panel panel-primary tag">
            <div class="panel-heading">
                <?= $tag['name']; ?>
            </div>
            <div class="panel-body">
                <?= $tag['description']; ?>
            </div>
        </div>
    </a>
    <br >
<?php
    endforeach
?>

</div>
<script>
    $(".tag").mouseover(function(){
        $(this).removeClass("panel-primary");
        $(this).addClass("panel-info");
    });

    $(".tag").mouseleave(function(){
        $(this).removeClass("panel-info");
        $(this).addClass("panel-primary");
    });
    
</script>


